import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ActionButton, YText } from '@/components/ui';
import { colors, radius, spacing, type } from '@/design/tokens';
import { useAuth } from '@/stores/auth-store';

export function AuthScreen() { const { signInWithEmail } = useAuth(); const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const submit = async () => { if (!email.includes('@')) { setError('Enter a valid email address.'); return; } setError(''); try { await signInWithEmail(email.trim()); setSent(true); } catch { setError('Couldn’t send the link. Try again in a moment.'); } }; return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={[styles.fieldLayer, styles.pointerNone]}><View style={[styles.colorField, styles.fieldOne]} /><View style={[styles.colorField, styles.fieldTwo]} /><View style={[styles.colorField, styles.fieldThree]} /></View><View style={styles.mark}><Ionicons name="sparkles" size={21} color={colors.brandInk} /></View><YText style={styles.wordmark}>Yubrio</YText>{sent ? <View style={styles.center}><View style={styles.sentIcon}><Ionicons name="mail-outline" size={28} color={colors.brandInk} /></View><YText style={type.title}>Check your inbox.</YText><YText style={styles.body}>{`Your sign-in link is on its way to ${email}.`}</YText><Pressable accessibilityRole="button" onPress={() => setSent(false)} style={styles.textButton}><YText style={styles.textButtonLabel}>Use a different email</YText></Pressable></View> : <View style={styles.form}><YText style={type.title}>See your people more.</YText><YText style={styles.body}>Sign in to see who’s free and open something spontaneous.</YText><YText style={styles.label}>EMAIL</YText><TextInput accessibilityLabel="Email address" autoCapitalize="none" autoComplete="email" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor={colors.faint} style={styles.input} />{error ? <YText style={styles.error}>{error}</YText> : null}<ActionButton label="Send sign-in link" icon="arrow-forward" onPress={submit} style={{ marginTop: 14 }} /><YText style={styles.privacy}>No password to remember. You can turn off emails anytime.</YText></View>}</KeyboardAvoidingView>; }

const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.canvas, paddingHorizontal: spacing.xxl, paddingTop: 86 }, pointerNone: { pointerEvents: 'none' }, fieldLayer: { ...StyleSheet.absoluteFill, overflow: 'hidden' }, colorField: { position: 'absolute', opacity: 0.12, transform: [{ rotate: '18deg' }] }, fieldOne: { width: 220, height: 90, top: 110, right: -110, backgroundColor: colors.electric }, fieldTwo: { width: 180, height: 74, bottom: 120, left: -100, backgroundColor: colors.coral }, fieldThree: { width: 150, height: 64, bottom: 38, right: -70, backgroundColor: colors.violet }, mark: { width: 46, height: 46, borderRadius: 16, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, wordmark: { fontSize: 21, fontWeight: '900', marginTop: 12, letterSpacing: -0.5 }, form: { flex: 1, justifyContent: 'center', paddingBottom: 100 }, body: { color: colors.muted, fontSize: 16, lineHeight: 23, fontWeight: '600', marginTop: 12, maxWidth: 330 }, label: { ...type.label, color: colors.muted, marginTop: 34 }, input: { minHeight: 54, borderRadius: radius.button, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 16, fontSize: 16, color: colors.ink, marginTop: 8 }, error: { color: colors.error, fontSize: 13, fontWeight: '700', marginTop: 8 }, privacy: { textAlign: 'center', color: colors.faint, fontSize: 12, lineHeight: 18, fontWeight: '600', marginTop: 18 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingBottom: 110 }, sentIcon: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center', marginBottom: 18 }, textButton: { marginTop: 28, minHeight: 44, justifyContent: 'center' }, textButtonLabel: { fontSize: 14, fontWeight: '800', color: colors.ink } });
