import React, { PropsWithChildren, useEffect, useState } from 'react';
import { Platform, Pressable, StyleProp, StyleSheet, Text, TextProps, View, ViewStyle } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { BlurView } from 'expo-blur';
import { GlassView, isGlassEffectAPIAvailable } from 'expo-glass-effect';
import * as Haptics from 'expo-haptics';
import Animated, { FadeInDown, FadeInRight, useAnimatedStyle, useReducedMotion, useSharedValue, withSpring } from 'react-native-reanimated';
import { activityMeta, colors, radius, shadow, spacing, type, ActivityType } from '@/design/tokens';
import { Person, Room } from '@/types';
import { copy } from '@/design/copy';
import { displayName, displayTitle } from '@/utils/display-name';

export function YText({ style, ...props }: TextProps) { return <Text {...props} style={[styles.text, style]} />; }
export function Screen({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[styles.screen, style]}>{children}</View>; }
export function ActivityIcon({ activity, size = 46 }: { activity: ActivityType; size?: number }) {
  const meta = activityMeta[activity];
  return <View style={[styles.activityIcon, { width: size, height: size, borderRadius: Math.round(size * 0.36), backgroundColor: meta.tint }]}><Ionicons name={meta.icon as any} size={size * 0.5} color={meta.color} /></View>;
}
export function Avatar({ person, size = 34 }: { person: Person; size?: number }) { return <View accessible={false} style={[styles.avatar, { width: size, height: size, borderRadius: size / 2, backgroundColor: person.color }]}><YText style={{ fontSize: size * 0.38, fontWeight: '800', color: colors.brandInk }}>{person.initials}</YText></View>; }
export function PersonRow({ person, detail, action }: { person: Person; detail: string; action?: React.ReactNode }) { return <View style={styles.personRow}><Avatar person={person} /><View style={styles.personCopy}><YText style={styles.personName}>{displayName(person.name)}</YText><YText style={styles.meta}>{detail}</YText></View>{action}</View>; }
export function SmallPill({ children, color = colors.surfaceMuted }: PropsWithChildren<{ color?: string }>) { return <View style={[styles.pill, { backgroundColor: color }]}><YText style={styles.pillText}>{children}</YText></View>; }
export function ActionButton({ label, icon, onPress, variant = 'primary', style, disabled }: { label: string; icon?: keyof typeof Ionicons.glyphMap; onPress?: () => void; variant?: 'primary' | 'secondary' | 'ghost'; style?: ViewStyle; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={() => { if (!disabled) { if (Platform.OS !== 'web') void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); onPress?.(); } }} style={({ pressed }) => [styles.actionButton, styles[`button_${variant}`], pressed && styles.actionButtonPressed, disabled && { opacity: 0.45 }, style]}>{icon && <Ionicons name={icon} size={18} color={variant === 'primary' ? colors.brandInk : colors.ink} />}<YText style={[styles.buttonLabel, variant === 'primary' && { color: colors.brandInk }]}>{label}</YText></Pressable>; }
export function SectionTitle({ children, action }: PropsWithChildren<{ action?: React.ReactNode }>) { return <View style={styles.sectionTitle}><YText style={type.section}>{children}</YText>{action}</View>; }
const webGlassStyle = { backgroundColor: 'rgba(30, 42, 37, 0.54)', backdropFilter: 'blur(24px) saturate(145%)', WebkitBackdropFilter: 'blur(24px) saturate(145%)' } as any;
export function GlassBackdrop({ intensity = 42, style }: { intensity?: number; style?: StyleProp<ViewStyle> }) { if (Platform.OS === 'ios' && isGlassEffectAPIAvailable()) return <GlassView colorScheme="dark" glassEffectStyle="regular" style={[StyleSheet.absoluteFill, styles.pointerNone, style]} />; if (Platform.OS === 'web') return <View style={[StyleSheet.absoluteFill, styles.pointerNone, webGlassStyle, style]} />; return <BlurView intensity={intensity} tint="dark" style={[StyleSheet.absoluteFill, styles.pointerNone, style]} />; }
export function RoomCard({ room, people }: { room: Room; people: Person[] }) { const meta = activityMeta[room.activity]; const peopleLabel = room.count <= 0 ? 'Open to your people' : room.count === 1 ? '1 person is in' : `${room.count} people are in`; const reducedMotion = useReducedMotion(); return <Animated.View entering={reducedMotion ? undefined : FadeInDown.duration(260)} style={[styles.roomCard, styles.roomMoment, roomMomentVisuals.roomMoment, { borderColor: colors.glassBorder }]}><View style={styles.roomTop}><ActivityIcon activity={room.activity} size={42} /><View style={styles.roomTitleWrap}><YText style={[styles.roomMomentKicker, { color: meta.color }]}>{roomStatus(room)}</YText><YText style={styles.roomMomentTitle}>{displayTitle(room.title)}</YText><YText style={styles.roomMomentTime}>{room.time}</YText></View></View><View style={styles.roomBottom}><View style={styles.roomPeople}>{people.slice(0, 3).map((person) => <Avatar key={person.id} person={person} size={28} />)}<View style={styles.roomMomentPeopleCopy}><YText style={styles.roomMomentPeopleNames} numberOfLines={1}>{people.slice(0, 2).map((person) => displayName(person.name)).join(' · ') || 'Be the first in'}</YText><YText style={styles.roomMomentPeople}>{peopleLabel}</YText></View></View>{room.detail ? <YText style={[styles.roomMomentLocation, { color: meta.color }]} numberOfLines={1}>{room.detail}</YText> : <YText style={styles.location}>{room.location ?? 'Undecided'}</YText>}</View></Animated.View>; }
export function RoomMomentCard({ room, people, onOpen, onYeb }: { room: Room; people: Person[]; onOpen?: () => void; onYeb?: () => void }) {
  const meta = activityMeta[room.activity];
  const reducedMotion = useReducedMotion();
  const peopleLabel = room.count <= 0 ? 'Open to your people' : room.count === 1 ? '1 person is in' : `${room.count} people are in`;
  const peopleNames = people.slice(0, 2).map((person) => displayName(person.name)).join(' · ');
  const [now, setNow] = useState(Date.now);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 30_000); return () => clearInterval(timer); }, []);
  const status = roomStatus(room, now);
  return <Animated.View entering={reducedMotion ? undefined : FadeInRight.duration(280)} style={[styles.roomMoment, roomMomentVisuals.roomMoment, { borderColor: colors.glassBorder }]}> 
    <Pressable accessibilityRole="button" accessibilityLabel={`Open ${displayTitle(room.title)}`} onPress={onOpen} style={({ pressed }) => [styles.roomMomentTapArea, pressed && styles.roomMomentBodyPressed]}>
      <View style={styles.roomMomentHeader}>
        <View style={styles.roomMomentType}><ActivityIcon activity={room.activity} size={38} /><View style={styles.roomMomentStatus}><YText style={[styles.roomMomentKicker, status === 'HAPPENING NOW' && styles.roomMomentKickerLive]}>{status}</YText></View></View>
        {(onYeb || room.joined) && <View style={styles.roomMomentActionSpacer} />}
      </View>
      <View style={styles.roomMomentBody}>
        <YText style={styles.roomMomentTitle}>{displayTitle(room.title)}</YText>
        <YText style={styles.roomMomentTime}>{room.time}</YText>
        {room.detail ? <YText style={styles.roomMomentDetail}>{room.detail}</YText> : null}
      </View>
      <View style={styles.roomMomentFooter}><View style={styles.roomPeople}>{people.slice(0, 3).map((person, index) => <Animated.View key={person.id} entering={reducedMotion ? undefined : FadeInRight.delay(index * 55).duration(220)}><Avatar person={person} size={27} /></Animated.View>)}<View style={styles.roomMomentPeopleCopy}><YText style={styles.roomMomentPeopleNames} numberOfLines={1}>{peopleNames || 'Be the first in'}</YText><YText style={styles.roomMomentPeople}>{peopleLabel}</YText></View></View><YText style={[styles.roomMomentLocation, { color: meta.color }]} numberOfLines={1}>{room.location ?? (room.online ? 'Online' : 'Undecided')}</YText></View>
    </Pressable>
    {(onYeb || room.joined) && <View style={styles.roomMomentActionOverlay}>{onYeb ? <MiniYebButton onPress={onYeb} title={displayTitle(room.title)} /> : <View accessible accessibilityLabel="You’re in" style={styles.miniYebJoined}><Ionicons name="checkmark" size={14} color={colors.brand} /><YText style={[styles.miniYebText, styles.miniYebJoinedText]}>You’re in</YText></View>}</View>}
  </Animated.View>;
}

function MiniYebButton({ onPress, title }: { onPress: () => void; title: string }) {
  const scale = useSharedValue(1);
  const animatedStyle = useAnimatedStyle(() => ({ transform: [{ scale: scale.value }] }), []);
  const join = () => {
    scale.set(withSpring(1.08, { damping: 9, stiffness: 420 }, () => { scale.set(withSpring(1, { damping: 12, stiffness: 420 })); }));
    if (Platform.OS !== 'web') void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    onPress();
  };
  return <Animated.View style={animatedStyle}><Pressable accessibilityRole="button" accessibilityLabel={`Yeb, join ${title}`} onPress={join} style={({ pressed }) => [styles.miniYeb, pressed && styles.miniYebPressed]}><Ionicons name="flash" size={14} color={colors.brandInk} /><YText style={styles.miniYebText}>Yeb!</YText></Pressable></Animated.View>;
}
export function AvailabilityCard({ person, expiresIn, note, onMessage }: { person: Person; expiresIn: string; note: string; onMessage?: () => void }) { const reducedMotion = useReducedMotion(); return <Animated.View entering={reducedMotion ? undefined : FadeInRight.duration(260)} style={[styles.availabilityCard, { borderColor: colors.glassBorder }]}><View style={styles.availabilityHeader}><View style={[styles.availabilityAvatar, { borderColor: person.color }]}><Avatar person={person} size={42} /></View><View style={styles.personCopy}><View style={styles.nameLine}><YText style={styles.personName}>{displayName(person.name)}</YText><View style={styles.freeBadge}><View style={styles.freeDot} /><YText style={styles.freeText}>FREE</YText></View></View><YText style={styles.meta}>{expiresIn}</YText></View>{onMessage && <Pressable accessibilityRole="button" accessibilityLabel={`Message ${displayName(person.name)}`} onPress={onMessage} style={styles.messageButton}><Ionicons name="arrow-up" size={17} color={colors.ink} style={styles.messageArrow} /></Pressable>}</View><YText style={styles.availabilityNote}>{note || 'Up for anything.'}</YText><View style={styles.availabilityFooter}><YText style={styles.availabilityFooterText}>Message while they’re free</YText><Ionicons name="arrow-forward" size={14} color={colors.muted} /></View></Animated.View>; }
export function YebButton({ joined, onPress }: { joined?: boolean; onPress: () => void }) { const reducedMotion = useReducedMotion(); const scale = useSharedValue(1); const animatedStyle = useAnimatedStyle(() => ({ transform: [{ scale: scale.get() }] }), []); const content = <><Ionicons name={joined ? 'checkmark' : 'flash'} size={19} color={colors.brandInk} /><YText style={[styles.yebLabel, joined && styles.yebJoinedLabel]}>{joined ? copy.room.joined : copy.room.join}</YText></>; return <Animated.View style={animatedStyle}>{joined ? <View accessible accessibilityLabel={copy.room.joined} style={[styles.yebButton, styles.yebJoined]}>{content}</View> : <Pressable accessibilityRole="button" accessibilityLabel="Yeb, join room" onPress={() => { if (!reducedMotion) scale.set(withSpring(1.08, { damping: 8 }, () => { scale.set(withSpring(1)); })); if (Platform.OS !== 'web') void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium); onPress(); }} style={({ pressed }) => [styles.yebButton, pressed && styles.yebButtonPressed]}>{content}</Pressable>}</Animated.View>; }

function roomStatus(room: Room, now = Date.now()) {
  if (typeof room.startsAt !== 'number' || typeof room.endAt !== 'number') return 'HAPPENING SOON';
  if (now < room.startsAt) return 'UP NEXT';
  if (now <= room.endAt) return 'HAPPENING NOW';
  return 'ENDED';
}

const roomMomentVisuals = {
  roomMoment: { minHeight: 252, backgroundColor: colors.surfaceStrong },
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas }, pointerNone: { pointerEvents: 'none' }, text: { color: colors.ink, fontSize: 15, fontWeight: '500' },
  activityIcon: { alignItems: 'center', justifyContent: 'center' }, avatar: { alignItems: 'center', justifyContent: 'center' },
  personRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.sm }, personCopy: { flex: 1 }, personName: { fontSize: 16, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 13, lineHeight: 18, fontWeight: '600' },
  pill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: radius.chip }, pillText: { fontSize: 11, fontWeight: '800', color: colors.ink },
  actionButton: { minHeight: 50, borderRadius: radius.button, borderBottomWidth: 4, paddingHorizontal: spacing.xl, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center' }, actionButtonPressed: { transform: [{ translateY: 2 }, { scale: 0.99 }], borderBottomWidth: 1 }, button_primary: { backgroundColor: colors.brand, borderBottomColor: colors.brandPressed }, button_secondary: { backgroundColor: colors.surfaceMuted, borderWidth: 1, borderColor: colors.glassBorder, borderBottomWidth: 4, borderBottomColor: colors.line }, button_ghost: { backgroundColor: 'transparent', borderBottomWidth: 0 }, buttonLabel: { fontSize: 15, fontWeight: '800', color: colors.ink },
  sectionTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md },
  glassFallback: { backgroundColor: colors.surface }, roomCard: { overflow: 'hidden', backgroundColor: colors.glassSurface, borderWidth: 1, borderColor: colors.glassBorder, borderRadius: radius.card, padding: spacing.lg, marginBottom: spacing.md, ...shadow.card }, roomTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, roomTitleWrap: { flex: 1 }, roomTitle: { fontSize: 17, fontWeight: '800', marginBottom: 3 }, liveDot: { width: 8, height: 8, borderRadius: 4 }, roomRule: { height: 1, backgroundColor: colors.line, marginVertical: spacing.md }, roomBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, roomPeople: { flexDirection: 'row', alignItems: 'center' }, peopleCount: { color: colors.muted, fontSize: 12, fontWeight: '800', marginLeft: 7 }, location: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  availabilityCard: { overflow: 'hidden', backgroundColor: colors.surface, borderWidth: 1, borderRadius: 22, padding: spacing.lg, marginRight: spacing.md, width: 274, ...shadow.card }, availabilityHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, availabilityAvatar: { borderWidth: 2, borderRadius: 24, padding: 2 }, nameLine: { flexDirection: 'row', gap: 7, alignItems: 'center', minWidth: 0 }, freeBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: activityMeta.availability.tint, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 999 }, freeDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: colors.brand }, freeText: { fontSize: 9, fontWeight: '900', color: colors.brand, letterSpacing: 0.6 }, messageButton: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.glassHighlight }, messageArrow: { transform: [{ rotate: '45deg' }] }, availabilityNote: { marginTop: spacing.xl, color: colors.ink, fontSize: 17, lineHeight: 21, fontWeight: '800' }, availabilityFooter: { marginTop: spacing.lg, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.glassBorder, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, availabilityFooterText: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  roomMoment: { minHeight: 238, overflow: 'hidden', backgroundColor: colors.surface, borderWidth: 1, borderRadius: 24, padding: spacing.lg, justifyContent: 'space-between', ...shadow.card }, roomMomentField: { position: 'absolute', width: 150, height: 76, top: -24, right: -34, opacity: 0.15, transform: [{ rotate: '18deg' }], borderBottomLeftRadius: 44 }, roomMomentTapArea: { flex: 1, justifyContent: 'space-between' }, roomMomentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, roomMomentActionSpacer: { width: 106, height: 38 }, roomMomentActionOverlay: { position: 'absolute', top: spacing.lg, right: spacing.lg, zIndex: 2 }, roomMomentType: { flexDirection: 'row', alignItems: 'center', gap: 10 }, roomMomentStatus: { gap: 5 }, roomMomentKicker: { ...type.label, color: colors.muted, fontSize: 9, letterSpacing: 1.1 }, roomMomentKickerLive: { color: colors.brand }, roomMomentBody: { flex: 1 }, roomMomentBodyPressed: { opacity: 0.78, transform: [{ translateY: 1 }] }, roomMomentTitle: { fontSize: 29, lineHeight: 32, fontWeight: '900', letterSpacing: -1, maxWidth: '94%', marginTop: spacing.lg }, roomMomentTime: { color: colors.ink, fontSize: 14, fontWeight: '800', marginTop: 8 }, roomMomentDetail: { color: colors.muted, fontSize: 13, fontWeight: '700', marginTop: 3 }, roomMomentFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm, marginTop: spacing.lg }, roomMomentPeople: { color: colors.muted, fontSize: 11, fontWeight: '700', marginTop: 2 }, roomMomentPeopleCopy: { marginLeft: 8, minWidth: 0 }, roomMomentPeopleNames: { color: colors.ink, fontSize: 11, fontWeight: '800', maxWidth: 125 }, roomMomentLocation: { fontSize: 12, fontWeight: '900', maxWidth: 105, textAlign: 'right' }, miniYeb: { minHeight: 38, borderRadius: 13, paddingHorizontal: 12, backgroundColor: colors.brand, borderBottomWidth: 3, borderBottomColor: colors.brandPressed, flexDirection: 'row', alignItems: 'center', gap: 5 }, miniYebPressed: { transform: [{ translateY: 2 }], borderBottomWidth: 1 }, miniYebJoined: { minHeight: 38, borderRadius: 13, paddingHorizontal: 10, backgroundColor: colors.surfaceMuted, borderWidth: 1, borderColor: colors.glassBorder, flexDirection: 'row', alignItems: 'center', gap: 4 }, miniYebText: { color: colors.brandInk, fontSize: 12, fontWeight: '900' }, miniYebJoinedText: { color: colors.brand },
  yebButton: { height: 54, borderRadius: radius.button, borderBottomWidth: 4, borderBottomColor: colors.brandPressed, paddingHorizontal: 23, backgroundColor: colors.brand, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, yebButtonPressed: { transform: [{ translateY: 2 }, { scale: 0.99 }], borderBottomWidth: 1 }, yebJoined: { backgroundColor: colors.brand, borderBottomWidth: 4, borderBottomColor: colors.brandPressed }, yebLabel: { fontSize: 17, fontWeight: '900', color: colors.brandInk }, yebJoinedLabel: { color: colors.brandInk },
});
